-- MySQL Script generated by MySQL Workbench
-- 12/03/14 21:05:29
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema judgefrog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `judgefrog` ;
CREATE SCHEMA IF NOT EXISTS `judgefrog` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `judgefrog` ;

-- -----------------------------------------------------
-- Table `judgefrog`.`Victims`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Victims` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Victims` (
  `VictimsId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Total` INT NOT NULL,
  `Minor` INT NOT NULL,
  `Foreigner` INT NOT NULL,
  `Female` INT NOT NULL,
  PRIMARY KEY (`VictimsId`),
  UNIQUE INDEX `VictimsId_UNIQUE` (`VictimsId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`ArrestChargeDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`ArrestChargeDetails` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`ArrestChargeDetails` (
  `ACDId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ChargeDate` DATE NOT NULL,
  `ArrestDate` DATE NOT NULL,
  `Detained` TINYINT(1) NOT NULL,
  `Role` TINYINT(1) NOT NULL DEFAULT 0,
  `LaborTraf` TINYINT(1) NOT NULL,
  `AdultSexTraf` TINYINT(1) NOT NULL,
  `MinorSexTraf` TINYINT(1) NOT NULL,
  `Fel_C` INT NOT NULL,
  `Fel_S` INT NOT NULL,
  PRIMARY KEY (`ACDId`),
  UNIQUE INDEX `Id_UNIQUE` (`ACDId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`Sentence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Sentence` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Sentence` (
  `SentenceId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DateTerminated` DATE NOT NULL,
  `Date` DATE NOT NULL,
  `Total` INT UNSIGNED NOT NULL,
  `Restitution` INT UNSIGNED NOT NULL,
  `AssetForfeit` TINYINT(1) NOT NULL,
  `Appeal` TINYINT(1) NOT NULL,
  `SupervisedRelease` INT UNSIGNED NOT NULL,
  `Probation` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`SentenceId`),
  UNIQUE INDEX `SentenceId_UNIQUE` (`SentenceId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`CaseTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`CaseTable` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`CaseTable` (
  `CaseId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NOT NULL,
  `Number` VARCHAR(64) NOT NULL,
  `Status` TINYINT(1) NOT NULL,
  `Num_Defendants` INT UNSIGNED NULL,
  `State` VARCHAR(2) NOT NULL,
  `FederalDistrict` INT UNSIGNED NOT NULL,
  `CourtId` INT UNSIGNED NOT NULL,
  `DefenseId` INT UNSIGNED NOT NULL,
  `VictimsId` INT UNSIGNED NOT NULL,
  `ACDId` INT UNSIGNED NOT NULL,
  `SentenceId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CaseId`),
  UNIQUE INDEX `CaseId_UNIQUE` (`CaseId` ASC),
  UNIQUE INDEX `Number_UNIQUE` (`Number` ASC),
  INDEX `fk_Case_VictimsId_idx` (`VictimsId` ASC),
  INDEX `fk_Case_ACDId_idx` (`ACDId` ASC),
  INDEX `fk_Case_SentenceId_idx` (`SentenceId` ASC),
  CONSTRAINT `fk_Case_VictimsId`
    FOREIGN KEY (`VictimsId`)
    REFERENCES `judgefrog`.`Victims` (`VictimsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_ACDId`
    FOREIGN KEY (`ACDId`)
    REFERENCES `judgefrog`.`ArrestChargeDetails` (`ACDId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_SentenceId`
    FOREIGN KEY (`SentenceId`)
    REFERENCES `judgefrog`.`Sentence` (`SentenceId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`Defendant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Defendant` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Defendant` (
  `DefendantId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NOT NULL,
  `Gender` TINYINT(1) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Race` INT NOT NULL,
  PRIMARY KEY (`DefendantId`),
  UNIQUE INDEX `Id_UNIQUE` (`DefendantId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`Charge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Charge` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Charge` (
  `ChargeId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ArrestChargeDetails_Id` INT UNSIGNED NOT NULL,
  `Counts` INT UNSIGNED NOT NULL,
  `CountsNolelProssed` INT UNSIGNED NOT NULL,
  `Statute` VARCHAR(45) NOT NULL,
  `PleaDismissed` INT UNSIGNED NOT NULL,
  `PleaGuilty` INT UNSIGNED NOT NULL,
  `TrialGuilty` INT UNSIGNED NOT NULL,
  `TrialNotGuilty` INT UNSIGNED NOT NULL,
  `Fines` INT UNSIGNED NOT NULL,
  `Sentence` INT UNSIGNED NOT NULL,
  `Probation` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ChargeId`),
  INDEX `fk_Charge_ArrestChargeDetails1_idx` (`ArrestChargeDetails_Id` ASC),
  UNIQUE INDEX `ChargeId_UNIQUE` (`ChargeId` ASC),
  CONSTRAINT `fk_Charge_ArrestChargeDetails1`
    FOREIGN KEY (`ArrestChargeDetails_Id`)
    REFERENCES `judgefrog`.`ArrestChargeDetails` (`ACDId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`Case_has_Defendant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Case_has_Defendant` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Case_has_Defendant` (
  `Case_CaseId` INT UNSIGNED NOT NULL,
  `Defendant_DefendantId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Case_CaseId`, `Defendant_DefendantId`),
  INDEX `fk_Case_has_Defendant_Defendant1_idx` (`Defendant_DefendantId` ASC),
  INDEX `fk_Case_has_Defendant_Case_idx` (`Case_CaseId` ASC),
  CONSTRAINT `fk_Case_has_Defendant_Case`
    FOREIGN KEY (`Case_CaseId`)
    REFERENCES `judgefrog`.`CaseTable` (`CaseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_has_Defendant_Defendant1`
    FOREIGN KEY (`Defendant_DefendantId`)
    REFERENCES `judgefrog`.`Defendant` (`DefendantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`Bail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Bail` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Bail` (
  `BailId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Type` TINYINT(1) NOT NULL,
  `Amount` DOUBLE NOT NULL,
  `ArrestChargeDetails_ACDId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`BailId`),
  UNIQUE INDEX `BailId_UNIQUE` (`BailId` ASC),
  INDEX `fk_Bail_ArrestChargeDetails1_idx` (`ArrestChargeDetails_ACDId` ASC),
  CONSTRAINT `fk_Bail_ArrestChargeDetails1`
    FOREIGN KEY (`ArrestChargeDetails_ACDId`)
    REFERENCES `judgefrog`.`ArrestChargeDetails` (`ACDId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`Judge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Judge` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Judge` (
  `JudgeId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(64) NOT NULL,
  `Race` INT NOT NULL,
  `Gender` TINYINT(1) NOT NULL,
  `Tenure` INT NOT NULL,
  `AppointedBy` INT NOT NULL,
  PRIMARY KEY (`JudgeId`),
  UNIQUE INDEX `JudgeId_UNIQUE` (`JudgeId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`Case_has_Judge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Case_has_Judge` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Case_has_Judge` (
  `Case_CaseId` INT UNSIGNED NOT NULL,
  `Judge_JudgeId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Case_CaseId`, `Judge_JudgeId`),
  INDEX `fk_Case_has_Judge_Judge1_idx` (`Judge_JudgeId` ASC),
  INDEX `fk_Case_has_Judge_Case1_idx` (`Case_CaseId` ASC),
  CONSTRAINT `fk_Case_has_Judge_Case1`
    FOREIGN KEY (`Case_CaseId`)
    REFERENCES `judgefrog`.`CaseTable` (`CaseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_has_Judge_Judge1`
    FOREIGN KEY (`Judge_JudgeId`)
    REFERENCES `judgefrog`.`Judge` (`JudgeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`OrganizedCrimeGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`OrganizedCrimeGroup` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`OrganizedCrimeGroup` (
  `OCGId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Size` INT NOT NULL,
  `Scope` INT NOT NULL,
  `Race` INT NOT NULL,
  PRIMARY KEY (`OCGId`),
  UNIQUE INDEX `OCGId_UNIQUE` (`OCGId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `judgefrog`.`Case_has_OrganizedCrimeGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `judgefrog`.`Case_has_OrganizedCrimeGroup` ;

CREATE TABLE IF NOT EXISTS `judgefrog`.`Case_has_OrganizedCrimeGroup` (
  `Case_CaseId` INT UNSIGNED NOT NULL,
  `OrganizedCrimeGroup_OCGId` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Case_CaseId`, `OrganizedCrimeGroup_OCGId`),
  INDEX `fk_Case_has_OrganizedCrimeGroup_OrganizedCrimeGroup1_idx` (`OrganizedCrimeGroup_OCGId` ASC),
  INDEX `fk_Case_has_OrganizedCrimeGroup_Case1_idx` (`Case_CaseId` ASC),
  CONSTRAINT `fk_Case_has_OrganizedCrimeGroup_Case1`
    FOREIGN KEY (`Case_CaseId`)
    REFERENCES `judgefrog`.`CaseTable` (`CaseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_has_OrganizedCrimeGroup_OrganizedCrimeGroup1`
    FOREIGN KEY (`OrganizedCrimeGroup_OCGId`)
    REFERENCES `judgefrog`.`OrganizedCrimeGroup` (`OCGId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
