//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class arrestchargedetail
    {
        public arrestchargedetail()
        {
            this.bails = new HashSet<bail>();
            this.casetables = new HashSet<casetable>();
            this.charges = new HashSet<charge>();
        }
    
        public long ACDId { get; set; }
        public System.DateTime ChargeDate { get; set; }
        public System.DateTime ArrestDate { get; set; }
        public bool Detained { get; set; }
        public bool Role { get; set; }
        public bool LaborTraf { get; set; }
        public bool AdultSexTraf { get; set; }
        public bool MinorSexTraf { get; set; }
        public int Fel_C { get; set; }
        public int Fel_S { get; set; }
    
        public virtual ICollection<bail> bails { get; set; }
        public virtual ICollection<casetable> casetables { get; set; }
        public virtual ICollection<charge> charges { get; set; }
    }
}
