//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class bail
    {
        public bail()
        {
            this.arrestchargedetails = new HashSet<arrestchargedetail>();
        }

        public bail(long bid, bool t, bool d, double a)
        {
            this.BailId = bid;
            this.Type = t;
            this.Detained = d;
            this.Amount = a;
            this.arrestchargedetails = new HashSet<arrestchargedetail>();
        }
    
        public long BailId { get; set; }
        public bool Type { get; set; }
        public bool Detained { get; set; }
        public double Amount { get; set; }
    
        public virtual ICollection<arrestchargedetail> arrestchargedetails { get; set; }
    }
}
