//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class bail
    {
        public long BailId { get; set; }
        public bool Type { get; set; }
        public double Amount { get; set; }
        public long ArrestChargeDetails_ACDId { get; set; }
    
        public virtual arrestchargedetail arrestchargedetail { get; set; }
    }
}
