//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class casetable
    {
        public casetable()
        {
            this.defendants = new HashSet<defendant>();
            this.hearings = new HashSet<hearing>();
            this.judges = new HashSet<judge>();
            this.motions = new HashSet<motion>();
            this.organizedcrimegroups = new HashSet<organizedcrimegroup>();
            this.prosecutors = new HashSet<prosecutor>();
        }
    
        public long CaseId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public bool Status { get; set; }
        public string Summary { get; set; }
        public bool GrandJury { get; set; }
        public long CourtId { get; set; }
        public long DefenseId { get; set; }
        public long VictimsId { get; set; }
        public long ACDId { get; set; }
        public long SentenceId { get; set; }
    
        public virtual arrestchargedetail arrestchargedetail { get; set; }
        public virtual court court { get; set; }
        public virtual defense defense { get; set; }
        public virtual sentence sentence { get; set; }
        public virtual victim victim { get; set; }
        public virtual ICollection<defendant> defendants { get; set; }
        public virtual ICollection<hearing> hearings { get; set; }
        public virtual ICollection<judge> judges { get; set; }
        public virtual ICollection<motion> motions { get; set; }
        public virtual ICollection<organizedcrimegroup> organizedcrimegroups { get; set; }
        public virtual ICollection<prosecutor> prosecutors { get; set; }
    }
}
