//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class casetable
    {
        public casetable()
        {
            this.defendants = new HashSet<defendant>();
            this.judges = new HashSet<judge>();
            this.organizedcrimegroups = new HashSet<organizedcrimegroup>();
        }

        public string ToString()
        {
            return this.Name;
        }
    
        public int CaseId { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public bool Status { get; set; }
        public int Num_Defendants { get; set; }
        public string State { get; set; }
        public int FederalDistrict { get; set; }
        public int VictimsId { get; set; }
        public int ACDId { get; set; }
        public int SentenceId { get; set; }
    
        public virtual arrestchargedetail arrestchargedetail { get; set; }
        public virtual sentence sentence { get; set; }
        public virtual victim victim { get; set; }
        public virtual ICollection<defendant> defendants { get; set; }
        public virtual ICollection<judge> judges { get; set; }
        public virtual ICollection<organizedcrimegroup> organizedcrimegroups { get; set; }
    }
}
