//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class charge
    {
        public long ChargeId { get; set; }
        public long ArrestChargeDetails_Id { get; set; }
        public long Counts { get; set; }
        public long CountsNolelProssed { get; set; }
        public string Statute { get; set; }
        public long PleaDismissed { get; set; }
        public long PleaGuilty { get; set; }
        public long TrialGuilty { get; set; }
        public long TrialNotGuilty { get; set; }
        public long Fines { get; set; }
        public long Sentence { get; set; }
        public long Probation { get; set; }
    
        public virtual arrestchargedetail arrestchargedetail { get; set; }
    }
}
