//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class charge
    {
        public int ChargeId { get; set; }
        public int ArrestChargeDetails_Id { get; set; }
        public int Counts { get; set; }
        public int CountsNolelProssed { get; set; }
        public string Statute { get; set; }
        public int PleaDismissed { get; set; }
        public int PleaGuilty { get; set; }
        public int TrialGuilty { get; set; }
        public int TrialNotGuilty { get; set; }
        public int Fines { get; set; }
        public int Sentence { get; set; }
        public int Probation { get; set; }
    
        public virtual arrestchargedetail arrestchargedetail { get; set; }
    }
}
