//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class hearing
    {
        public hearing()
        {
            this.casetables = new HashSet<casetable>();
        }
    
        public long HearingId { get; set; }
        public int Type { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<casetable> casetables { get; set; }
    }
}
