//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class judgefrogEntities : DbContext
    {
        public judgefrogEntities()
            : base("name=judgefrogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arrestchargedetail> arrestchargedetails { get; set; }
        public virtual DbSet<bail> bails { get; set; }
        public virtual DbSet<casetable> casetables { get; set; }
        public virtual DbSet<charge> charges { get; set; }
        public virtual DbSet<court> courts { get; set; }
        public virtual DbSet<defendant> defendants { get; set; }
        public virtual DbSet<defense> defenses { get; set; }
        public virtual DbSet<hearing> hearings { get; set; }
        public virtual DbSet<judge> judges { get; set; }
        public virtual DbSet<motion> motions { get; set; }
        public virtual DbSet<organizedcrimegroup> organizedcrimegroups { get; set; }
        public virtual DbSet<prosecutor> prosecutors { get; set; }
        public virtual DbSet<sentence> sentences { get; set; }
        public virtual DbSet<victim> victims { get; set; }
    }
}
