//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class sentence
    {
        public sentence()
        {
            this.casetables = new HashSet<casetable>();
        }
    
        public long SentenceId { get; set; }
        public System.DateTime DispositionDate { get; set; }
        public System.DateTime SentenceDate { get; set; }
        public int JailTime { get; set; }
        public int ProbationTime { get; set; }
        public int SuspendedTime { get; set; }
        public double Fines { get; set; }
        public int CommServ { get; set; }
        public bool COR { get; set; }
        public bool CCD_Id { get; set; }
    
        public virtual ICollection<casetable> casetables { get; set; }
    }
}
