//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeniorDesignWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class sentence
    {
        public sentence()
        {
            this.casetables = new HashSet<casetable>();
        }
    
        public long SentenceId { get; set; }
        public System.DateTime DateTerminated { get; set; }
        public System.DateTime Date { get; set; }
        public long Total { get; set; }
        public long Restitution { get; set; }
        public bool AssetForfeit { get; set; }
        public bool Appeal { get; set; }
        public long SupervisedRelease { get; set; }
        public long Probation { get; set; }
    
        public virtual ICollection<casetable> casetables { get; set; }
    }
}
